WebBasicsREST has been done
vitalikulsha/UpSkill_Lab1_JavaBasics pull request #4
Opened 2021-11-16 11:16 UTC by vitalikulsha

WebBasicsREST has been done

2021-11-22 19:42 UTC, AlehDrazdou requested changes

2021-11-22 19:42 UTC, AlehDrazdou commented on WebBasicsREST/data/log/log.log
> +2021-11-15 17:27:00 INFO  [http-nio-8080-exec-1]: Category received successfully! id = 3
Логи обычно не добавляются в репозиторий и по-хорошему должны быть добавлены в .gitignore файл - https://ru.hexlet.io/courses/git_base/lessons/git_gitignore/theory_unit

2021-11-22 19:42 UTC, AlehDrazdou commented on WebBasicsREST/pom.xml
> +			<version>8.0.27</version>
Версии обычно выносятся в <properties> блок

2021-11-22 19:42 UTC, AlehDrazdou commented on WebBasicsREST/src/main/java/io/github/vitalikulsha/WebBasicsREST/controller/AuthorController.java
> +        } catch (CategoryNotFoundException e) {
Смотрю у тебя почти везде повторяется два catch, убирай их из `Controller `и добавляй `RestExceptionHandler` с аннотацией - @RestControllerAdvice - вот пример как это применять - https://coderoad.ru/28902374/Spring-Boot-REST-обработка-исключений-службы#39705512

После добавляния этого общего handler у тебя в Controller код будет намного чище.

2021-11-24 19:31 UTC, vitalikulsha commented
update the code per the review

2021-11-25 19:51 UTC, AlehDrazdou commented on WebBasicsREST/src/main/java/io/github/vitalikulsha/WebBasicsREST/model/Author.java
> +        Author model = new Author();
Заюзай плиз тут @Mapper(componentModel = "spring") 
https://www.baeldung.com/mapstruct
https://coderoad.ru/38807415/Mapstruct-%D0%BA%D0%B0%D0%BA-%D1%8F-%D0%BC%D0%BE%D0%B3%D1%83-%D0%B2%D0%B2%D0%B5%D1%81%D1%82%D0%B8-%D0%B7%D0%B0%D0%B2%D0%B8%D1%81%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C-spring-%D0%B2-%D1%81%D0%B3%D0%B5%D0%BD%D0%B5%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9-%D0%BA%D0%BB%D0%B0%D1%81%D1%81-Mapper

2021-11-25 19:54 UTC, AlehDrazdou commented on WebBasicsREST/src/main/java/io/github/vitalikulsha/WebBasicsREST/model/Category.java
> +        Category model = new Category();
Юзаем @Mapper от MapStruct

2021-11-25 19:54 UTC, AlehDrazdou commented on WebBasicsREST/src/main/java/io/github/vitalikulsha/WebBasicsREST/service/AuthorService.java
> +    private Optional<AuthorEntity> getAuthorFromDB(Long id) throws AuthorNotFoundException {
никаких `fromDB` не должно быть

2021-11-27 08:41 UTC, vitalikulsha commented
add MapStruct in the code

2021-11-27 09:15 UTC, merged